# Numpy array dizisi oluşturma

In [2]:
import numpy as np

In [3]:
## Liste oluşturma

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [4]:
# Listelerde olduğu gibi, her bir öğeye köşeli parantez yoluyla erişebiliriz:

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


# Tür¶
Dizinin türünü kontrol edersek numpy.ndarray elde ederiz:

In [5]:
type(a)

numpy.ndarray

# dtype¶ 
NumPy dizisinde saklanan değerlerin türünü kontrol et

In [6]:
a.dtype

dtype('int64')

# Değer atama
Dizinin değerini değiştirebiliriz. <code>c</code> dizisini ele alalım:

In [7]:
c = np.array([20, 1, 2, 3, 4 ])
c

## elemöanlarını bu şekilde değiştirebilriiz.
c[0] = 100
c[4] = 0

In [8]:
ap = np.array([10, 2, 30, 40, 50])
ap[1] = 20
ap

array([10, 20, 30, 40, 50])

## Slicing (dilimleme)
<code>[başlangıç:bitiş:adım] <code>

In [9]:
# d değişkenine c'nin 1'den 3.değerine kadar ata

d = c[1:4]
d


array([1, 2, 3])

In [10]:
## Yeni değerlere karşılık gelen indeksleri aşağıdaki gibi atayabiliriz:
c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [12]:
arrr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arrr[1::2]

array([2, 4, 6, 8])

# Vektör ekleme

In [15]:
a = np.array([1,3,5])
b = np.array([2,4,6])
c = a+b
c               ## 3,7,11

array([ 3,  7, 11])

# Skaler ile Vektör Çarpımı

In [16]:
skaler = np.array([1,2,3,4])
vektor = 2
d = skaler*vektor
d

array([2, 4, 6, 8])

#  Hadamard ürünü
### Aynı konumdaki sayılar birbiriyle çarpılır.
### Matrislerin boyutları birbiriyle tam olarak aynı olmalıdır

In [23]:
## Yol 1 

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

sonuc = a * b
sonuc

## Yol 2 

sonuc2 = np.multiply(a,b)
sonuc2

array([[ 5, 12],
       [21, 32]])

# Nokta Ürünü

In [25]:
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

# Nokta Çarpımı (Matris Çarpımı)

sonuc_dot = np.dot(A, B)
# [ [1*5 + 2*7,  1*6 + 2*8],
#   [3*5 + 4*7,  3*6 + 4*8] ]

sonuc_dot

array([[19, 22],
       [43, 50]])