In [3]:
import numpy as np

In [5]:
arr = np.array([[1,2,3],[4,5,6]])

In [7]:
print(arr.shape)              ## 2 satır 3 sütun var bunda diye sonuç verir : (2, 3 )

(2, 3)


In [8]:
print(arr.dtype)              ## arr değişkeninin dloat64 mü int64 mü olduğunu söyler. bellek yönetimi

int64


In [9]:
print(arr.reshape(3,2))       ## veriyi bozmadan sadece şeklini değiştirecek. 3 grup yap 2 şerli olsun.

[[1 2]
 [3 4]
 [5 6]]


## Döngü Kurmadan Döngüye almak

In [10]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
print(matrix[1][:2])          ## 1.kümedeki 0 ve 1. index gelsin

[4 5]


In [20]:
grup1 = np.arange(10,51)              ## burada 10 ve 51 arası bütün sayılar tek tek gelir. fakat 51 dahil değill!!

In [23]:
print(grup1[grup1 %2 ==0])

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [35]:
grup2 =np.random.rand(5,3)               ## 0 ve 1 arasında random sayı ürettik ve 5x3 lük bir dizi oldu

In [36]:
print(grup2.mean(axis = 0))             ## sütunların ortalamasını bul !!!!!   axis = 0 sütun demek

[0.44991533 0.66985121 0.57382498]


In [37]:
print(grup2.sum(axis = 1))             ## satırların toplamını tek tek al !!!!!! axis = 1 satır demek

[1.5862372  2.09282657 1.70593354 1.3177737  1.76518656]


## Z scoru Uzun hesaplama

In [47]:
grup3 = np.random.randint(0,100, (3,3))

In [49]:
print('Orjinal Matris:\n', grup3)

Orjinal Matris:
 [[89 45 21]
 [59 42 37]
 [86 32 38]]


In [53]:
## 2. Adım: Sütun ortalamalarını al (Sonuç (3,) boyutunda bir dizidir)
ortalamalar = grup3.mean(axis=0)
print('Sütun Ortalamaları:',ortalamalar)

Sütun Ortalamaları: [78.         39.66666667 32.        ]


In [55]:
## 3. Adım: Çıkarma işlemi
normalize_matris = grup3 - ortalamalar
print('Ortalaması Çıkartılmış Matris:\n', normalize_matris)

Ortalaması Çıkartılmış Matris:
 [[ 11.           5.33333333 -11.        ]
 [-19.           2.33333333   5.        ]
 [  8.          -7.66666667   6.        ]]


In [57]:
z_score = (grup3 - grup3.mean(axis = 0)) / grup3.std(axis= 0)

In [58]:
print(z_score)

[[ 0.81537425  0.95961623 -1.41226963]
 [-1.4083737   0.4198321   0.64194074]
 [ 0.59299945 -1.37944833  0.77032889]]


## Z Scoru hesaplaması

In [60]:
data = np.random.randint(0,100, (10,5))
print(data)

[[71 63 28 39 59]
 [68 45  5 48 99]
 [69 49 53 59 61]
 [26 34 60 61 83]
 [20 99 23 16  9]
 [65 87 73 14 30]
 [87 76 73 91  5]
 [81 36 93 79 33]
 [70 82 40 97 80]
 [36 63 98 18 59]]


In [61]:
mu = data.mean(axis = 0)
sigma = data.std(axis = 0)

In [65]:
z_score = (data - mu) / sigma

In [66]:
print(z_score)

[[ 0.52919511 -0.01887633 -0.91526281 -0.45314026  0.23952674]
 [ 0.39350405 -0.86831101 -1.70665546 -0.14418099  1.57023083]
 [ 0.43873441 -0.67954775 -0.0550534   0.23343589  0.30606194]
 [-1.50617069 -1.38740999  0.18580523  0.30209351  1.03794919]
 [-1.7775528   1.67999304 -1.08730469 -1.24270285 -1.42385338]
 [ 0.257813    1.11370325  0.63311412 -1.31136046 -0.72523373]
 [ 1.25288073  0.59460428  0.63311412  1.33195775 -1.55692379]
 [ 0.98149862 -1.29302835  1.32128165  0.92001205 -0.62543092]
 [ 0.48396476  0.87774917 -0.50236229  1.53793059  0.93814639]
 [-1.05386718 -0.01887633  1.49332353 -1.17404523  0.23952674]]


In [79]:
z_score.mean(axis = 0)

array([ 1.33226763e-16,  6.24500451e-17, -2.22044605e-17, -1.11022302e-16,
        8.32667268e-17])

In [78]:
z_score.std(axis = 0)

array([1., 1., 1., 1., 1.])

## 2 KÜMEYİ BİRLEŞTİRME

In [92]:
A = np.random.randint(0,100,(5,3))

In [93]:
B = np.random.randint(0,100,(3,2))

In [94]:
C = A@B

In [95]:
print(C.shape)

(5, 2)


## Lineer Regresyon

In [96]:
## örneğimiz bir evin metrekaresı ve fiyatı olacak
X = np.array([[50], [60],[70], [80],[90], [100]])

In [97]:
Y = np.array([[500], [610], [690], [820],[905],[1010]])

In [115]:
## w = np.random.randn(1,1)          ## rastgele bir ağırlık atadık
w = np.array([[10]])

In [116]:
## b = np.random.randn(1)            ## rastgele bir bias
b = np.array([1])

In [117]:
y_pred = X @ w+b

In [118]:
print(y_pred)

[[ 501]
 [ 601]
 [ 701]
 [ 801]
 [ 901]
 [1001]]


In [119]:
error = y_pred -Y 

In [120]:
mse = np.mean(error**2)

In [121]:
mse

np.float64(110.16666666666667)

## burası makine öğrenmesinde aslında iş yapıyor lineer denklem

In [122]:
# NumPy'ın lineer cebir kütüphanesini kullanarak en iyi çözümü bul
# (X matrisine 1'lerden oluşan bir sütun eklememiz gerekir bias için ama şimdilik kafan karışmasın)
from numpy.linalg import inv

In [123]:
# Normal Equation (Matematiksel kesin çözüm)
# Not: Bu biraz ileri seviye bir matris işlemidir, sadece gücü gör diye veriyorum
W_optimal = inv(X.T @ X) @ X.T @ Y
print("Mükemmel Ağırlık (W):", W_optimal)

Mükemmel Ağırlık (W): [[10.08309859]]


In [124]:
# Şimdi bu W_optimal ile tahmin yap
y_final_pred = X @ W_optimal
final_mse = np.mean((y_final_pred - Y)**2)
print("Final Mükemmel MSE:", final_mse)

Final Mükemmel MSE: 79.97652582159601
